### ISSUE TITLE
Create a user if not exist

### ISSUE THREAD

**Issue by fredroo** [meramsey/cyberpanel-fixperms#9]
I need to create a user for a domain imported by python import cPanel script, after import I take a look at users and groups, The script doesn't create a CyberPanel user for each domain, right I have this problem, all my domains are in the root user

Can you update your script to do it

@meramsey

**Comment by meramsey** [comment]
Sorry that is unfortunately not something this script would ever be responsible for. 

The scripts intent is to properly fix perms on valid and existing accounts and domains with user defined home directory it can parse.

I recommend fixing your import script to have it create accounts and specify home directory s for domains that it is importing. then you should have no problems or alternatively write or adjust the current script on your own for your needs.

**Comment by fredroo** [comment]
@meramsey thanks for your time
